select 
P.PROCESS_DATE   AS  TARIH,
P.ETL_DATE   AS  DATA_TARIHI,
P.IP_ID   AS  MUSTERI_NO,
C.CUSTOMER_LONG_NAME   AS  MÜSTERI_ADI,
P.LOAN_REFERENCE   AS  KREDI_NUMARASI,
P.BRANCH_ID   AS  SUBE_KODU,
P.CURR_CODE   AS  PARA_KODU,
P.INSTALLMENT_ID   AS  TAKSIT_SIRA_NO,
P.INSTALLMENT_DATE   AS  TAKSIT_TARIHI,
P.INSTALLMENT_PRINCIP_AMNT   AS  TAKSIT_ANAPARA,
P.INSTALLMENT_INTEREST_AMNT   AS  TAKSIT_FAIZ,
( P.INSTALLMENT_PRINCIP_AMNT + P.INSTALLMENT_INTEREST_AMNT) AS TAKSIT_TUTARI,
P.TRANSACTION_DATE   AS  ODEME_TARIHI,
P.TRANS_PRINCIPAL_AMNT   AS  ODENEN_ANAPARA,
P.TRANS_INTEREST_AMNT   AS  ODENEN_FAIZ,
(P.TRANS_PRINCIPAL_AMNT + P.TRANS_INTEREST_AMNT ) AS ODEME_TUTARI,
P.PAYMENT_CODE   AS  ODEME_TIP
--L.OPEN_DATE   AS  ACILIS_TARIHI,
--L.ESTIMATED_END_DATE   AS  VADE_TARIHI,
--L.USAGE_DATE   AS  KULLANDIRIM_TARIHI,
--L.ACCT_OPEN_BAL_AMNT_ORIG   AS  ACILIS_BAKIYESI_ORJ
from TGARYSR.TDM_LOAN_PAYMENT P 
LEFT JOIN TGARYSR.TDWINPA C
ON  
 P.IP_ID=C.IP_ID
 AND P.PROCESS_DATE=C.PROCESS_DATE 
WHERE 
P.PROCESS_DATE = TO_DATE(20240831,'YYYYMMDD') AND
P.LOAN_REFERENCE IN (
select LOAN_REF_NO from TGARYSR.TDM_LOAN L
WHERE L.PROCESS_DATE = TO_DATE(20240831,'YYYYMMDD')
AND L.CLOSED_IND ='A'
AND L.BALANCE_ORIG <>0);


KREDI ODEME PLAN bu tabloda mevcut sql ile kapalı olan alanlar hgelmiyor ama inner joın ile olabilirse L: den  de istenen alanlar eklenebilr mi?
ayrıca bu tablo çıktı olarak KREDI_NUMARASI VE TAKSIT_SIRA_NO alanları bazında sıralı gelmeli.



