SELECT 
L.ETL_DATE              AS  DATA_TARIHI,
L.PROCESS_DATE          AS  TARIH,
L.GL_ACCOUNT_NUM        AS  DK_NUMARASI,
L.IP_ID                 AS  MUSTERI_NO,
C.CUSTOMER_LONG_NAME    AS  MUSTERI_ADI,
C.COUNTRY_OF_RES_ID     AS  ULKE,
C.SME_TYPE              AS  KOBI,
C.RISK_GROUP_CODE       AS  RGK,
L.BRANCH_ID             AS  SUBE_KODU,
L.ACCOUNT_NUM           AS  HESAP_NO,
L.LOAN_REF_NO           AS  KREDI_NUMARASI,
L.LOAN_TYPE             AS  KREDI_TIP,
L.CURR_CODE             AS  PARA_KODU,
L.BALANCE_TL            AS  ANAPARA, ----iskonto iştira kredisi yok olursa düzeltme gerekir.
L.BALANCE_ORIG          AS  BAKIYE_ORJ,
L.BALANCE_USD           AS  BAKIYE_USD,
L.CURR_INTEREST_RATE    AS  BASIT_FAIZ_ORANI,
L.COMPOUND_INTEREST     AS  BILESIK_FAIZ,
L.IRR_RATE              AS  IRR_ORANI,
L.OPEN_DATE             AS  ACILIS_TARIHI,
L.USAGE_DATE            AS  KULLANDIRIM_TARIHI,
L.ESTIMATED_END_DATE    AS  VADE_TARIHI,
L.REDISCOUNT_AMOUNT     AS  REESKONT_TUTARI,
L.IRR_AMOUNT            AS  IRR_TUTARI,
L.ACCT_OPEN_BAL_AMNT_ORIG   AS  ACILIS_BAKIYESI_ORJ,
L.ISKONTO_ISTIRA_FLG        AS  ISKONTO_ISTIRA_FLG,
L.ISKONTO_ISTIRA_FAIZ       AS  ISKONTO_ISTIRA_FAIZ,
L.LOAN_CLASS                AS  KREDI_SINIF,
L.LIMIT_CODE                AS  LIMIT_NUMARASI,
L.PROC_TYPE                 AS  KREDI_KAYNAK,
L.LOAN_NAME                 AS  KREDI_ADI,
C.SECTOR_CODE               AS  NACE_KOD,
C.FINANCE_CODE              AS  FKK,
'YENI_KULLANDIRIM'  AS TIP
FROM TGARYSR.TDM_LOAN L
left join TGARYSR.TDWINPA C
on L.PROCESS_DATE=C.PROCESS_DATE
and L.IP_ID=C.IP_ID
WHERE 
L.PROCESS_DATE = TO_DATE(20240831,'YYYYMMDD')--son tarih 
AND
 ((L.OPEN_DATE BETWEEN  TO_DATE(20240101,'YYYYMMDD') AND  TO_DATE(20240831,'YYYYMMDD')) --ilktarih son tarih arası
 OR (USAGE_DATE BETWEEN  TO_DATE(20240101,'YYYYMMDD') AND  TO_DATE(20240831,'YYYYMMDD'))) --ilktarih son tarih arası
AND L.CLOSED_IND ='A'
AND L.BALANCE_ORIG <>0
